import type { Task } from '@entities/task';

/**
 * Demo uchun mock task data
 * Haqiqiy API qo'shilganida o'chiriladi
 */
export const MOCK_TASKS: Task[] = [
  // Yangi lidlar
  {
    id: '1',
    taskNumber: '#12901',
    status: 'new_leads',
    priority: 'medium',
    productName: 'iPhone 13 Pro Max',
    customerName: 'Alisher Odilov',
    phoneNumber: '+998 90 000 06 12',
    assignedUsers: [
      { id: 'u1', name: 'Aziz Karimov', avatarUrl: undefined },
      { id: 'u2', name: 'Bobur Toshev', avatarUrl: undefined },
      { id: 'u3', name: 'Charos Rahimova', avatarUrl: undefined },
      { id: 'u4', name: 'Davron Saidov', avatarUrl: undefined },
      { id: 'u5', name: 'Eldor Umarov', avatarUrl: undefined },
    ],
    pickupPerson: "O'zim",
    deliveryPerson: "O'zim",
    source: 'telegram',
    date: '2025-02-17',
    createdAt: '2025-02-17T10:00:00Z',
    updatedAt: '2025-02-17T10:00:00Z',
  },
  {
    id: '2',
    taskNumber: '#12902',
    status: 'new_leads',
    priority: 'high',
    productName: 'Samsung Galaxy S24',
    customerName: 'Dilshod Rahimov',
    phoneNumber: '+998 91 123 45 67',
    assignedUsers: [
      { id: 'u1', name: 'Aziz Karimov', avatarUrl: undefined },
      { id: 'u2', name: 'Bobur Toshev', avatarUrl: undefined },
    ],
    pickupPerson: "O'zim",
    deliveryPerson: "O'zim",
    source: 'phone',
    date: '2025-02-17',
    createdAt: '2025-02-17T11:00:00Z',
    updatedAt: '2025-02-17T11:00:00Z',
  },
  {
    id: '3',
    taskNumber: '#12903',
    status: 'new_leads',
    priority: 'low',
    productName: 'MacBook Pro 14',
    customerName: 'Feruza Karimova',
    phoneNumber: '+998 93 456 78 90',
    assignedUsers: [
      { id: 'u3', name: 'Charos Rahimova', avatarUrl: undefined },
    ],
    pickupPerson: 'Kuryer',
    deliveryPerson: "O'zim",
    source: 'website',
    date: '2025-02-16',
    createdAt: '2025-02-16T14:00:00Z',
    updatedAt: '2025-02-16T14:00:00Z',
  },
  // Tamirlanmoqda
  {
    id: '4',
    taskNumber: '#12904',
    status: 'in_repair',
    priority: 'medium',
    productName: 'iPhone 13 Pro Max',
    customerName: 'Alisher Odilov',
    phoneNumber: '+998 90 000 06 12',
    assignedUsers: [
      { id: 'u1', name: 'Aziz Karimov', avatarUrl: undefined },
      { id: 'u2', name: 'Bobur Toshev', avatarUrl: undefined },
      { id: 'u3', name: 'Charos Rahimova', avatarUrl: undefined },
    ],
    pickupPerson: "O'zim",
    deliveryPerson: "O'zim",
    source: 'telegram',
    date: '2025-02-17',
    createdAt: '2025-02-17T09:00:00Z',
    updatedAt: '2025-02-17T12:00:00Z',
  },
  // Tayyor
  {
    id: '5',
    taskNumber: '#12905',
    status: 'ready',
    priority: 'medium',
    productName: 'iPhone 13 Pro Max',
    customerName: 'Alisher Odilov',
    phoneNumber: '+998 90 000 06 12',
    assignedUsers: [
      { id: 'u1', name: 'Aziz Karimov', avatarUrl: undefined },
      { id: 'u2', name: 'Bobur Toshev', avatarUrl: undefined },
      { id: 'u3', name: 'Charos Rahimova', avatarUrl: undefined },
    ],
    pickupPerson: "O'zim",
    deliveryPerson: "O'zim",
    source: 'telegram',
    date: '2025-02-17',
    createdAt: '2025-02-17T08:00:00Z',
    updatedAt: '2025-02-17T14:00:00Z',
  },
  // Mijozga berildi
  {
    id: '6',
    taskNumber: '#12906',
    status: 'delivered',
    priority: 'low',
    productName: 'iPhone 13 Pro Max',
    customerName: 'Alisher Odilov',
    phoneNumber: '+998 90 000 06 12',
    assignedUsers: [
      { id: 'u1', name: 'Aziz Karimov', avatarUrl: undefined },
      { id: 'u2', name: 'Bobur Toshev', avatarUrl: undefined },
    ],
    pickupPerson: "O'zim",
    deliveryPerson: "O'zim",
    source: 'telegram',
    date: '2025-02-17',
    createdAt: '2025-02-15T10:00:00Z',
    updatedAt: '2025-02-17T16:00:00Z',
  },
];
